### ISSUE TITLE
Plans to release hovernet inference weights

### ISSUE THREAD

**Issue by shubhaminnani** [AIRMEC/im4MEC#1]
Hi,
This is great repository and the work is quite interesting.

Do you plan to release hovernet trained weights and codes for interpreability?

Thanks!

**Comment by jjhbw** [comment]
Hi @shubhaminnani ,

I'm afraid we are not planning to release the trained model weights at this time. Regarding the code: we did not meaningfully modify the code from the original HoVerNet authors. That code can be found here https://github.com/vqdang/hover_net
