### ISSUE TITLE
MOCO v2

### ISSUE THREAD

**Issue by Rainydu184** [AIRMEC/im4MEC#3]
Hi, you really did a good job. Would you please share the MOCO pth file ？

**Comment by jjhbw** [comment]
Hi @Rainydu184 , thanks for you kind words. I'm afraid we're not planning to publish the trained model weights for the foreseeable future.

**Comment by Rainydu184** [comment]
Hi, @jjhbw . I am downloading the TCGA_UCEC datasets, but the label perplex me. I find the label _UCEC_CN_HIGH UCEC_CN_LOW UCEC_POLE UCEC_MSI UCEC_POLE_ ， how do the lable transfer to _POLE, p53, MMRd, NSMP_。 Is it just a different name for the same thing?

**Comment by Rainydu184** [comment]
_I found the words in the paper:_
POLE mutational status is assessed by use of
targeted DNA sequencing of exons 9–14 (POLEmut
). Loss
of expression of mismatch repair proteins (MMR
deficient [MMRd]) by immunohistochemistry is an
excellent surrogate for microsatellite instability.
Tumours with a high copy number are characterised by
TP53 mutations and can be identified by abnormal,
mutant-like cellular tumour antigen p53 expression
(p53abn). Tumours with a low copy number are referred
to as having no specific molecular profile (NSMP).
