### ISSUE TITLE
"sample_tiles.py" and "preprocess.py"

### ISSUE THREAD

**Issue by JAAY-AI** [AIRMEC/im4MEC#6]
Patches have been extracted in "sample_tiles.py", why do we still need to use the original WSI in "preprocess.py"?

**Comment by jjhbw** [comment]
The purpose of `sample_tiles.py` is to create a dataset for the self-supervised training of the feature extractor. `Preprocess.py` is used to convert WSIs into feature bags using the trained feature extractor.
